apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: abobakr99/capstone
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP